### PR TITLE
[Feat]: Auth

### PR DESCRIPTION
**Pull request by parthpandyappp**
- Login, Logout, Signup
- User profile's Data population
- User profile updation
- Navigating the third person's profile by username with `/profile/username` route
- re-Signup user upon losing the user data upon refresh from DB.

**note**: 
- Currently for third-party profile navigation you can test: https://deploy-preview-3--lattice-networks.netlify.app/profile/testcool/
- Log in using Test credentials.

### CODE REVIEW

**Review by sonishreyas — APPROVED** [review]
Code looks good, really like the folder structure and UI

**Comment by parthpandyappp** [comment]
Thanks @sonishreyas for the PR review :+1:

**Review by Logan1x — APPROVED** [review]
Hey Parth, Your commit looks good
- nice use of redux.
- use params URL is good.
- Naming of variables is semantic.

**Comment by parthpandyappp** [comment]
Thanks Khushal for sharing your valuable feedback :grin:

**Pull request merged**
