### PR TITLE
[Design]: Pages, Components

### PR DESCRIPTION
**Pull request by parthpandyappp**
- Separated components and pages.
- Added designs to them.

**note**: 
- This PR is only meant for the design screens of Lattice Networks. Functionality for the same will be released in future commits.
- Currently below pages are in action:
    - `/`
    - `/profile`
    - `/explore`
    - `/login`
    - `/signup`
    - `404 Not Found`

### CODE REVIEW

**Review by TejasShekar — APPROVED** [review]
- Routes seems to be not working. Add the redirects file for netlify.
- Rest looks good to merge.

**Comment by parthpandyappp** [comment]
Yes, I need to configure netlify for these routes. Thankyou, I'll update it.

**Comment by chanchal16** [comment]
In your UI the nav icons size is a bit larger which is looking quite odd, either try to reduce the size or increase the font size of the brand name. Other than that looks good to merge!

**Review by chanchal16 — APPROVED** [review]
In your UI the nav icons size is a bit larger which is looking quite odd, either try to reduce the size or increase the font size of the brand name. Other than that looks good to merge!

**Comment by parthpandyappp** [comment]
Cool. Thanks for the review Chancal. I'll look into and fix it in the next commit😁

**Comment by parthpandyappp** [comment]
Worked upon suggestions, made few changes in accordance with that & above are the commits for the same :+1:

**Review by sonishreyas — COMMENTED** [review]
Code looks good. like the folder structure

**Pull request merged**
